-- Migration 089: remove public INSERT policy from job-applications Storage
--
-- Supersedes only the permissive policy created by migration 084.
-- Public uploads must use the signed upload URL generated by get-upload-url.
-- This migration is intentionally small and does not change SELECT, UPDATE,
-- DELETE, bucket configuration, or any other Storage policy.

DROP POLICY IF EXISTS "storage: job-applications insert"
ON storage.objects;
